slevin-VirtualBox# cat /home/slevin/frontend/.travis.yml 
language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t slevinhome/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true slevinhome/docker-react npm run test
