sudo: required
 - docker

before_install:
 - docker build -t slevinhome/docker-react -f Dockerfile.dev .

script:
 - docker run slevinhome/docker-react npm run test -- --coverage


deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-495010293839"
 bucket_path: "docker"
 on:
   branch: master
 access_key_id : $AWS_ACCESS_KEY
 secret_access_key:
   secure: "$AWS_SECRET_KEY"
 
