language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lstas180877/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lstas180877/docker-react npm run test


